"""
Authentication Router
======================
Provides /api/v1/auth/login endpoint for Admin Console sign-in.
Validates credentials against the USER_CREDENTIALS environment variable.
No registration endpoint is exposed — accounts are provisioned only via config.
"""

from __future__ import annotations

import hashlib
import logging
import secrets

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

from app.api.schemas.auth import LoginRequest, LoginResponse
from app.config import settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/auth", tags=["Authentication"])

# ---------------------------------------------------------------------------
# Credential resolution
# ---------------------------------------------------------------------------


def _parse_credentials() -> dict[str, str]:
    """
    Parse USER_CREDENTIALS environment variable into a username→password dict.
    Format: "username:password,username2:password2"
    """
    cred_map: dict[str, str] = {}
    raw = getattr(settings, "user_credentials", "") or ""
    for pair in raw.split(","):
        pair = pair.strip()
        if ":" not in pair:
            continue
        parts = pair.split(":", 2)  # at most 3 parts (user:pass:email)
        if len(parts) >= 2:
            username = parts[0].strip().lower()
            password = parts[1].strip()
            if username:
                cred_map[username] = password
    return cred_map


def _role_for(username: str) -> str:
    """Determine the role based on the username."""
    if username.lower() == "admin":
        return "System Administrator"
    return "User"


def _make_token(username: str) -> str:
    """Generate a deterministic-per-session token (not a secret key store)."""
    rand = secrets.token_hex(16)
    return f"rac_{hashlib.sha256((username + rand).encode()).hexdigest()[:40]}"


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/login",
    response_model=LoginResponse,
    summary="Admin Console Sign-In",
    description=(
        "Authenticate with username and password. "
        "Credentials are validated against server-side configured accounts. "
        "No self-registration is supported."
    ),
)
def login(payload: LoginRequest) -> LoginResponse | JSONResponse:
    """Validate credentials and return an auth token on success."""
    username = (payload.username or "").strip()
    password = (payload.password or "").strip()

    if not username or not password:
        return JSONResponse(
            status_code=400,
            content={
                "success": False,
                "message": "Username and password are required.",
            },
        )

    logger.info("AUTH | ADMIN_LOGIN_ATTEMPT | username=%s", username)

    creds = _parse_credentials()
    stored_password = creds.get(username.lower())

    if stored_password is None or stored_password != password:
        logger.warning("AUTH | ADMIN_LOGIN_FAILED | username=%s | reason=invalid_credentials", username)
        return JSONResponse(
            status_code=401,
            content={"success": False, "message": "Invalid username or password."},
        )

    role = _role_for(username)
    token = _make_token(username)
    logger.info("AUTH | ADMIN_LOGIN_SUCCESS | username=%s", username)

    return LoginResponse(
        success=True,
        token=token,
        username=username,
        role=role,
        avatar_letter=username[0].upper(),
        message="Login successful",
    )


@router.get(
    "/me",
    summary="Verify Session Token",
    description="Validates the Bearer token from the Authorization header. Returns 200 if valid, 401 if invalid or missing.",
)
def verify_me(request: Request) -> JSONResponse:
    """Return 200 if the Authorization header carries a valid-looking session token."""
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        return JSONResponse(
            status_code=401,
            content={
                "success": False,
                "message": "Missing or malformed Authorization header.",
            },
        )

    token = auth_header[len("Bearer ") :]
    # Tokens generated by _make_token() look like: rac_<40 hex chars>
    if token.startswith("rac_") and len(token) == 44:
        return JSONResponse(
            status_code=200, content={"success": True, "message": "Token is valid."}
        )

    return JSONResponse(
        status_code=401, content={"success": False, "message": "Invalid token."}
    )
